apiVersion: apps/v1
kind: Deployment
metadata:
 name: redis-exporter
 namespace: monitoring
spec:
 selector:
   matchLabels:
     app: redis-exporter
 replicas: 1
 template:
   metadata:
     labels:
       app: redis-exporter
     annotations:
       prometheus.io/port: "9121"
       prometheus.io/scrape: "true"
   spec:
     containers:
     - name: redis-exporter
       image: oliver006/redis_exporter:latest
       ports:
         - containerPort: 9121
       env:
       - name: REDIS_ADDR
         value: 'redis://redis-clusterip-service.wodio.svc.cluster.local:6379' # this is redis cluster ip
       - name: REDIS_USER
         valueFrom:
           secretKeyRef:
             name: redis-exporter-auth
             key: user
       - name: REDIS_PASSWORD
         valueFrom:
           secretKeyRef:
             name: redis-exporter-auth
             key: password
       resources:
         limits:
           memory: "256Mi"
           cpu: "256m"